import random

from .pair_simplifier import pair_simplifier
from .checking_who_won_two_pair_scenario import checking_who_won_two_pair_scenario
from .two_pairs_per_player import two_pairs_per_player
from .create_deck_of_cards import create_deck_of_cards
from .deal_a_card import deal_a_card
from .create_players import create_players
